// <auto-generated />
namespace NaturalFrut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Relacion_VentaYProductosXVenta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Relacion_VentaYProductosXVenta));
        
        string IMigrationMetadata.Id
        {
            get { return "201806180350566_Relacion_VentaYProductosXVenta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
