// <auto-generated />
namespace NaturalFrut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambiosEnModel_CondicionIVA_ViewModel_Cliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiosEnModel_CondicionIVA_ViewModel_Cliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201805030408571_cambiosEnModel_CondicionIVA_ViewModel_Cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
