// <auto-generated />
namespace NaturalFrut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Model_ProductoXVenta_Descuento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_ProductoXVenta_Descuento));
        
        string IMigrationMetadata.Id
        {
            get { return "201807202259335_Model_ProductoXVenta_Descuento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
