// <auto-generated />
namespace NaturalFrut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class models_saldoparcial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(models_saldoparcial));
        
        string IMigrationMetadata.Id
        {
            get { return "201811020038030_models_saldoparcial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
