// <auto-generated />
namespace NaturalFrut.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Seed_CondicionIVA_TipoCliente_UandR_TU : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seed_CondicionIVA_TipoCliente_UandR_TU));
        
        string IMigrationMetadata.Id
        {
            get { return "201808102322154_Seed_CondicionIVA_TipoCliente_UandR_TU"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
